SIMPLE_MELEE = [
    {"Name": "Club", "Damage": "1d4", "Type": "bludgeoning", "Notes": "Light"},
    {"Name": "Dagger", "Damage": "1d4", "Type": "piercing",
        "Notes": "Finesse, light, thrown (range 20/60)"},
    {"Name": "Greatclub", "Damage": "1d8", "Type": "bludgeoning",
        "Notes": "Two-handed"},
    {"Name": "Handaxe", "Damage": "1d6", "Type": "slashing",
        "Notes": "Light, thrown (range 20/60)"},
    {"Name": "Javelin", "Damage": "1d6", "Type": "piercing",
        "Notes": "Thrown (range 30/120)"},
    {"Name": "Light Hammer", "Damage": "1d4", "Type": "bludgeoning",
        "Notes": "Light, thrown (range 20/60)"},
    {"Name": "Mace", "Damage": "1d6", "Type": "bludgeoning", "Notes": ""},
    {"Name": "Quarterstaff", "Damage": "1d6", "Type": "bludgeoning",
        "Notes": "Versatile (1d8)"},
    {"Name": "Sickle", "Damage": "1d4", "Type": "slashing", "Notes": "Light"},
    {"Name": "Spear", "Damage": "1d6", "Type": "piercing",
        "Notes": "Thrown (range 20/60), versatile (1d8)"},
]
SIMPLE_RANGED = [
    {"Name": "Crossbow, light", "Damage": "1d8", "Type": "piercing",
        "Notes": "Ammunition (range 80/320), loading, two-handed"},
    {"Name": "Dart", "Damage": "1d4", "Type": "piercing",
        "Notes": "Finesse, thrown (range 20/60)"},
    {"Name": "Shortbow", "Damage": "1d6", "Type": "piercing",
        "Notes": "Ammunition (range 80/320), two-handed"},
    {"Name": "Sling", "Damage": "1d4", "Type": "bludgeoning",
        "Notes": "(range 30/120)"},
]
MARTIAL_MELEE = [
    {"Name": "Battleaxe", "Damage": "1d8", "Type": "slashing",
        "Notes": "Versatile (1d10)"},
    {"Name": "Flail", "Damage": "1d8", "Type": "bludgeoning", "Notes": ""},
    {"Name": "Glaive", "Damage": "1d10", "Type": "slashing",
        "Notes": "Heavy, reach, two-handed"},
    {"Name": "Greataxe", "Damage": "1d12", "Type": "slashing",
        "Notes": "Heavy, two-handed"},
    {"Name": "Greatsword", "Damage": "2d6", "Type": "slashing",
        "Notes": "Heavy, two-handed"},
    {"Name": "Halberd", "Damage": "1d10", "Type": "slashing",
        "Notes": "Heavy, reach, two-handed"},
    {"Name": "Lance", "Damage": "1d12", "Type": "piercing",
        "Notes": "Reach, special"},
    {"Name": "Longsword", "Damage": "1d8", "Type": "slashing",
        "Notes": "Versatile (1d10)"},
    {"Name": "Maul", "Damage": "2d6", "Type": "bludgeoning",
        "Notes": "Heavy, two-handed"},
    {"Name": "Morningstar", "Damage": "1d8", "Type": "piercing", "Notes": ""},
    {"Name": "Pike", "Damage": "1d10", "Type": "piercing",
        "Notes": "Heavy, reach, two-handed"},
    {"Name": "Rapier", "Damage": "1d8", "Type": "piercing", "Notes": "Finesse"},
    {"Name": "Scimitar", "Damage": "1d6", "Type": "slashing",
        "Notes": "Finesse, light"},
    {"Name": "Shortsword", "Damage": "1d6", "Type": "piercing",
        "Notes": "Finesse, light"},
    {"Name": "Trident", "Damage": "1d6", "Type": "piercing",
        "Notes": "Thrown (range 20/60), versatile (1d8)"},
    {"Name": "War Pick", "Damage": "1d8", "Type": "piercing", "Notes": ""},
    {"Name": "Warhammer", "Damage": "1d8", "Type": "bludgeoning",
        "Notes": "Versatile (1d10)"},
    {"Name": "Whip", "Damage": "1d4", "Type": "slashing",
        "Notes": "Finesse, reach"},
]
MARTIAL_RANGED = [
    {"Name": "Blowgun", "Damage": "1", "Type": "piercing",
        "Notes": "Ammunition (range 25/100), loading"},
    {"Name": "Crossbow, hand", "Damage": "1d6", "Type": "piercing",
        "Notes": "Ammunition (range 30/120), light, loading"},
    {"Name": "Crossbow, heavy", "Damage": "1d10", "Type": "piercing",
        "Notes": "Ammunition (range 100/400), heavy, loading,"},
    {"Name": "Longbow", "Damage": "1d8", "Type": "piercing",
        "Notes": "Ammunition (range 150/600), heavy, two-handed"},
    {"Name": "Net", "Damage": "—", "Type": "-",
        "Notes": "Special, thrown (range 5/15) "},
]
